---

- name: is_aws init
  set_fact:
    is_aws: false

- name: Check for AWS
  set_fact:
    is_aws: true
  when: ansible_bios_version.find("amazon") != -1

- name: Create /etc/hosts
  when: kube_aws_create_etc_hosts and is_aws
  template: src=hosts.j2 dest=/etc/hosts
