---
- name: Copy AWS configuration file
  copy: src=~/.aws/config dest=/etc/aws.conf owner=kube mode=0600 directory_mode=0700

- name: Convert AWS configuration file
  replace: dest=/etc/aws.conf regexp="default" replace="Global"

- name: Create /etc/aws directory
  file: path=/etc/aws state=directory owner=kube mode=0700

- name: Copy AWS credentials
  copy: src=~/.aws/credentials dest=/etc/aws/credentials owner=kube mode=0600
